Fix build error (due to -Werror)
dferry/events/eventdispatcher.cpp: In member function ‘void EventDispatcherPrivate::tryCompactTimerSerials()’:
dferry/events/eventdispatcher.cpp:215:9: error: variable ‘numDeadEntries’ set but not used [-Werror=unused-but-set-variable=]
  215 |     int numDeadEntries = 0;
      |         ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors